# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embed',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_embed_embed', serialize=False, to='cms.CMSPlugin')),
                ('source', models.CharField(max_length=255, null=True, verbose_name='Source')),
                ('allow_fullscreen', models.BooleanField(default=False, verbose_name='Allow fullscreen')),
                ('ratio', models.CharField(choices=[('21by9', '21:9'), ('16by9', '16:9'), ('4by3', '4:3'), ('1by1', '1:1')], default='16by9', max_length=5, verbose_name='Ratio')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
