# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailhosting', '0004_auto_20170611_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='from_members',
        ),
        migrations.RemoveField(
            model_name='list',
            name='is_private',
        ),
        migrations.AddField(
            model_name='list',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Is the list subscribeable from non registered users'),
        ),
        migrations.AlterField(
            model_name='list',
            name='check_sender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Allow all senders'), (1, 'Allow all members'), (2, 'Allow only priviledged addresses')], default=2, help_text='Check sender email address'),
        ),
        migrations.AlterField(
            model_name='list',
            name='to_members',
            field=models.BooleanField(default=False, help_text='Send mail to all members'),
        ),
    ]
