# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_markdown', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='show_toc',
            field=models.BooleanField(default=False, verbose_name='Table of Contents'),
        ),
        migrations.AlterField(
            model_name='markdown',
            name='raw_text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
