"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

from .settings_default import *  # NOQA

LANGUAGES = [
    ('de', "Deutsch"),
]
CMS_TEMPLATES = (
    ("template_clean.html", gettext("Full width Template")),
)

MANAGERS = ADMINS
INTERNAL_IPS = ('127.0.0.1', '85.25.139.15')
DEFAULT_FROM_EMAIL = "sebastian@elmnt.de"
SERVER_EMAIL = "noreply@elmnt.de"

# Application definition
INSTALLED_APPS += [
]
