# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_use_django_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_valid',
            field=models.BooleanField(default=False, help_text='Indicates if the user has a valid email address.', verbose_name='Has valid email'),
        ),
    ]
