# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ACL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64, verbose_name='Topic')),
                ('permission', models.PositiveSmallIntegerField(choices=[(1, 'Subscribe'), (2, 'Subscribe and Publish')], default=1, verbose_name='Permission')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Access Control List',
                'verbose_name_plural': 'Access Control Lists',
            },
        ),
        migrations.AlterUniqueTogether(
            name='acl',
            unique_together=set([('user', 'topic')]),
        ),
    ]
